"""Derive the static root-policy tier tables from downloaded community statistics.

Input: the raw API responses kept beside iteration-043 (`external/`, with provenance.json).
Output: spire_exact/planning/policy_data.py, a generated module so the tables are covered by the
source version hash. The rules are the ones pre-registered in experiments/iteration-043/plan.md
(arms `pick` and `elo`). The tables are a source of rollout diversity, never card values:
iteration-043 found no arm better than the native policy on its own.

    python tools/build_policy_tiers.py --external experiments/iteration-043/external
    python tools/build_policy_tiers.py --external experiments/iteration-043/external --check
"""
from pathlib import Path
import argparse, hashlib, json, pprint, sys

ROOT = Path(__file__).resolve().parents[1]
TARGET = ROOT / 'spire_exact/planning/policy_data.py'
FILES = ('cards-metrics-a10.json', 'cards-metrics-a10-ironclad.json', 'cards-scores-a10-skip.json')


def tiers_pick(metrics, ironclad):
    """Per-act tiers from human pick rates; cut points from the 100 cards Ironclad holds most often."""
    rows = {r['id']: r for r in metrics['rows'] if not r['upgraded']}
    held = {r['id']: r['picks'] for r in ironclad['rows'] if not r['upgraded']}
    pool = sorted((i for i in rows if rows[i]['offered'] >= 2000 and rows[i]['pick_rate'] is not None and i in held),
                  key=lambda i: (-held[i], i))[:100]
    cuts = []
    for act in range(3):
        values = sorted(rows[i]['pick_rate_by_act'][act] for i in pool if rows[i]['pick_rate_by_act'][act] is not None)
        cuts.append([values[int(len(values) * q)] for q in (.1, .3, .7, .9)])
    tiers = {}
    for card, row in rows.items():
        if row['offered'] < 2000 or row['pick_rate'] is None:
            continue
        per_act = []
        for act in range(3):
            rate = row['pick_rate_by_act'][act]
            if rate is None:
                per_act.append(0); continue
            p10, p30, p70, p90 = cuts[act]
            per_act.append(2 if rate >= p90 else 1 if rate >= p70 else -2 if rate <= p10 else -1 if rate <= p30 else 0)
        if any(per_act):
            tiers['card:' + card] = per_act
    return tiers


def tiers_elo(scores):
    """Tiers from the Bradley-Terry rating relative to SKIP: +-70 Elo is a 60 % preference, +-191 is 75 %."""
    skip = scores['SKIP']['elo']
    tiers = {}
    for card, row in scores.items():
        if card == 'SKIP' or row.get('elo') is None:
            continue
        gap = row['elo'] - skip
        tier = 2 if gap >= 191 else 1 if gap >= 70 else -2 if gap <= -191 else -1 if gap <= -70 else 0
        if tier:
            tiers['card:' + card] = [tier, tier, tier]
    return tiers


def build(external: Path) -> str:
    raw = {name: (external / name).read_bytes() for name in FILES}
    data = {name: json.loads(blob.decode('utf-8')) for name, blob in raw.items()}
    tiers = {'pick': tiers_pick(data[FILES[0]], data[FILES[1]]), 'elo': tiers_elo(data[FILES[2]])}
    for table in tiers.values():
        if any(type(t) is not int or not -2 <= t <= 2 for row in table.values() for t in row):
            raise SystemExit('tiers must be integers within -2..2')
    source = {'site': 'https://spire-codex.com public API, A10 bracket', 'rules': 'experiments/iteration-043/plan.md (arms pick, elo)',
              'sha256': {name: hashlib.sha256(blob).hexdigest() for name, blob in raw.items()}}
    body = ['"""Generated by tools/build_policy_tiers.py - do not edit by hand.',
            '',
            'Static per-label tiers (one integer per act) derived from community A10 statistics.',
            'A source of rollout diversity only: on its own neither table beat the native policy',
            '(experiments/iteration-043/results.md). Never a card value, a bound or a proof.',
            '"""',
            'SOURCE = ' + pprint.pformat(source, width=120, sort_dicts=True),
            '',
            'TIERS = ' + pprint.pformat({name: dict(sorted(table.items())) for name, table in sorted(tiers.items())},
                                        width=120, compact=True, sort_dicts=True),
            '']
    return '\n'.join(body)


def main():
    p = argparse.ArgumentParser()
    p.add_argument('--external', type=Path, required=True)
    p.add_argument('--check', action='store_true', help='fail when the generated module differs from the one on disk')
    a = p.parse_args()
    text = build(a.external)
    if a.check:
        if not TARGET.is_file() or TARGET.read_text(encoding='utf-8') != text:
            raise SystemExit('policy_data.py is not what these inputs generate')
        print('policy_data.py matches'); return
    TARGET.write_text(text, encoding='utf-8', newline='\n')
    print(json.dumps({'written': str(TARGET), 'bytes': len(text.encode('utf-8'))}))


if __name__ == '__main__':
    main()
