"""Build the display-only STS2 Wiki name snapshot; never import game descriptions.

Run manually to refresh. The dashboard has no runtime dependency on the Wiki.
"""
from concurrent.futures import ThreadPoolExecutor
from datetime import date
from pathlib import Path
import argparse
import json
import re
import urllib.request

ROOT = Path(__file__).resolve().parents[1]
BASE = 'https://slaythespire2.net/zh-CN/'
CACHE = ROOT / 'outputs' / 'route-zh-wiki'


def wiki(path, refresh=False):
    cache = CACHE / (path.replace('/', '__') + '.html')
    if cache.exists() and not refresh:
        html = cache.read_text(encoding='utf-8')
    else:
        request = urllib.request.Request(BASE + path, headers={'User-Agent': 'Mozilla/5.0'})
        with urllib.request.urlopen(request, timeout=30) as response:
            html = response.read().decode('utf-8')
        cache.parent.mkdir(parents=True, exist_ok=True)
        cache.write_text(html, encoding='utf-8')
    chunks = re.findall(r'self\.__next_f\.push\((\[1,.*?\])\)</script>', html)
    return ''.join(json.loads(chunk)[1] for chunk in chunks)


def field(flight, name):
    marker = '"' + name + '":'
    pos = flight.find(marker)
    if pos < 0:
        raise ValueError('Wiki data field missing: ' + name)
    return json.JSONDecoder().raw_decode(flight[pos + len(marker):])[0]


def build(refresh=False):
    sources = []
    names = {}
    events = []
    for path, key in [('card', 'cards'), ('relic', 'relics'), ('potion', 'potions'),
                      ('monster', 'monsters'), ('event', 'events'), ('ancient', 'ancients')]:
        flight = wiki(path, refresh)
        # Read the page's initial dataset, not navigation/translation messages.
        initial = field(flight, 'initial')
        rows = initial[key]
        if not rows:
            raise ValueError('Empty Wiki dataset: ' + key)
        names.setdefault(key, {}).update({row['id']: row['name'] for row in rows})
        # The main catalog omits generated/status cards and special potions.
        # Wiki hover references supply their exact names and class/ID aliases.
        tips = initial.get('hoverTips')
        for tip_id, tip in (tips if isinstance(tips, dict) else {}).items():
            head, _, ident = tip_id.partition(':')
            category = {'card': 'cards', 'potion': 'potions', 'relic': 'relics'}.get(head)
            if category and tip.get('title'):
                names.setdefault(category, {}).setdefault(ident, tip['title'])
        sources.append(BASE + path)
        if key == 'events':
            events = rows

    def event_options(row):
        path = 'event/' + row['slug']
        detail = field(wiki(path, refresh), 'event')
        result = {}
        for page in detail.get('pages', []):
            for option in page.get('options', []):
                section, option_id = option['key'].split('.', 1)
                title = re.sub(r'<[^>]*>', '', option['title']).strip('[]')
                if title:
                    result[f"{row['id']}.pages.{section}.options.{option_id}"] = title
        return BASE + path, result

    options = {}
    with ThreadPoolExecutor(max_workers=2) as executor:
        for source, result in executor.map(event_options, events):
            sources.append(source)
            options.update(result)
    # Two status cards absent from this Wiki's catalog and hover references.
    # Name/ID pairs checked against the Chinese STS2 Wiki's Card.tabx table.
    names['cards'].update({'WITHER': '凋萎', 'INFECTION': '感染'})
    sources.extend(['https://sts2.huijiwiki.com/wiki/Data%3ACard.tabx',
                    'https://sts2.huijiwiki.com/wiki/%E6%84%9F%E6%9F%93'])
    return {'schema': 'spireboard-route-zh/v1', 'retrieved': date.today().isoformat(),
            'sources': sources, 'names': names, 'event_options': options}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--refresh', action='store_true')
    args = parser.parse_args()
    data = build(args.refresh)
    target = ROOT / 'dashboard' / 'web' / 'route_zh_data.js'
    target.write_text('// Generated by tools/build_route_zh.py; display names only.\n'
                      '(function(root){const data=' + json.dumps(data, ensure_ascii=False, indent=2) +
                      ';if(typeof module!=="undefined"&&module.exports)module.exports=data;'
                      'else root.routeZhData=data;})(typeof globalThis!=="undefined"?globalThis:this);\n',
                      encoding='utf-8')
    print({key: len(value) for key, value in data['names'].items()},
          'event_options', len(data['event_options']), 'output', target)


if __name__ == '__main__':
    main()
